export default {
  "login": "akshatpathak26",
  "id": 94177449,
  "node_id": "U_kgDOBZ0IqQ",
  "avatar_url": "https://avatars.githubusercontent.com/u/94177449?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/akshatpathak26",
  "html_url": "https://github.com/akshatpathak26",
  "followers_url": "https://api.github.com/users/akshatpathak26/followers",
  "following_url": "https://api.github.com/users/akshatpathak26/following{/other_user}",
  "gists_url": "https://api.github.com/users/akshatpathak26/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/akshatpathak26/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/akshatpathak26/subscriptions",
  "organizations_url": "https://api.github.com/users/akshatpathak26/orgs",
  "repos_url": "https://api.github.com/users/akshatpathak26/repos",
  "events_url": "https://api.github.com/users/akshatpathak26/events{/privacy}",
  "received_events_url": "https://api.github.com/users/akshatpathak26/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Akshat Pathak",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 27,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2021-11-12T12:40:20Z",
  "updated_at": "2022-05-07T23:52:06Z"
  };
